num1 = float(input("Enter the first number\n"))
num2 = float (input("Enter the second number\n"))
print(num1,"+",num2,"=",num2+num2)
print(num1,"-",num2,"=",num2-num2)
print(num1,"/",num2,"=",num2/num2)
print(num1,"*",num2,"=",num2*num2)